Accept {request_options, [{Key, Value}]} and pass to hackney:request/5
for-GET/katt pull request #81
Opened 2021-04-16 20:08 UTC by brucify

Example:
```erl
katt:run("hello.apib", [{request_options, [{certfile, "path"}, {keyfile, "path"}]).
```

Fixes #80

2021-04-16 20:40 UTC, andreineculau commented
Cursory review on my phone: looks good. Thanks for the input. At first one might say "but why when you can redefine the request function?" but the default function is far from a oneliner.

Quick thoughts:
- rename to hackney_options for clarity and future proofing
- I believe the request function should accept Params as the last argument instead of Options. This way you can also extract the hackney options only where they are needed e.g. not in a case where you override the request fun and use smth other than hackney
- Maybe make sure that the options passed to hackney don't have duplicate keys when you merge with recv_timeout and insecure. I can't check right now Hackney's behavior.

PS: not sure if it's logged in the git history but this has been implemented before and later removed because i thought it's a nice to have without any real demand. Great that there's demand! :)

2021-04-17 05:32 UTC, brucify commented
Thx for the feedback. Fixed in a new commit

2021-05-02 14:29 UTC, andreineculau requested changes
Sorry for the long turnaround time! Looks neat!
I have one change request though, if possible. See inline.

2021-05-02 14:29 UTC, andreineculau commented on src/katt_callbacks.erl
> +  katt_util:external_http_request(Url, Method, Hdrs, Body, Timeout, Params).
send only the hackney_options as HackneyOpts, not the entire katt params to keep katt_util:external_http_request minimalistic

2021-05-29 22:56 UTC, merged